only create dataset if it doesn't exist

diff --git a/storj/node/create-node b/storj/node/create-node
--- a/storj/node/create-node
+++ b/storj/node/create-node
@@ -20,12 +20,16 @@ if [ -z "$NODE" ] || [ -z "$PORT" ] || [ -z "$AUTH_TOKEN" ] || [ -z "$STORJ_INST
 fi
 
 # Check if the pool with the matching node name exists
-sudo zpool list ${NODE} >/dev/null 2>&1 || { echo "Pool ${NODE} not found"; exit 1; }
-DATASET=${NODE}/storj
-DATA_ROOT=/mnt/${DATASET}
-echo "Creating Storj dataset in ${DATASET}"
-sudo zfs create ${DATASET}
-sudo chown -R $(id -u):$(id -g) ${DATA_ROOT}
+sudo zpool list "${NODE}" >/dev/null 2>&1 || { echo "Pool ${NODE} not found"; exit 1; }
+DATASET="${NODE}/storj"
+DATA_ROOT="/mnt/${DATASET}"
+
+if ! sudo zfs list "${DATASET}" >/dev/null 2>&1; then
+  echo "Creating Storj dataset in ${DATASET}"
+  sudo zfs create "${DATASET}"
+fi
+
+sudo chown -R "$(id -u):$(id -g)" "${DATA_ROOT}"
 
 printf "Creating the storage node directories in ${DATA_ROOT}\n\n"
 IDENTITY_DIR="${DATA_ROOT}/identity"
