use printf only for multiple line breaks

diff --git a/storj/node/create-node b/storj/node/create-node
--- a/storj/node/create-node
+++ b/storj/node/create-node
@@ -15,32 +15,32 @@ STORJ_SECRETS="${_SHARED_STORJ_DIR}/secrets.env"
 
 # Sanity checks
 if [ -z "$NODE" ] || [ -z "$PORT" ] || [ -z "$AUTH_TOKEN" ] || [ -z "$STORJ_INSTANCE" ]; then
-  printf "Error: NODE, PORT, AUTH_TOKEN, and STORJ_INSTANCE arguments are required."
+  echo "Error: NODE, PORT, AUTH_TOKEN, and STORJ_INSTANCE arguments are required."
   exit 1
 fi
 
 # Check if the pool with the matching node name exists
-sudo zpool list ${NODE} >/dev/null 2>&1 || { printf "Pool ${NODE} not found"; exit 1; }
+sudo zpool list ${NODE} >/dev/null 2>&1 || { echo "Pool ${NODE} not found"; exit 1; }
 DATASET=${NODE}/storj
 DATA_ROOT=/mnt/${DATASET}
-printf "Creating Storj dataset in ${DATASET}"
+echo "Creating Storj dataset in ${DATASET}"
 sudo zfs create ${DATASET}
 sudo chown -R $(id -u):$(id -g) ${DATA_ROOT}
 
-printf "Creating the storage node directories in ${DATA_ROOT}\n"
+printf "Creating the storage node directories in ${DATA_ROOT}\n\n"
 IDENTITY_DIR="${DATA_ROOT}/identity"
 mkdir -p ${IDENTITY_DIR}
 mkdir -p ${DATA_ROOT}/config
 
 NODE_NAME="patzm-${STORJ_INSTANCE}-${NODE}"
-printf "Using node name: ${NODE_NAME}"
-printf "Create & authorize the identity file with the following commands, then move it to ${IDENTITY_DIR}"
-printf "This might take a while ... Run it on a powerful machine!\n"
-printf "mkdir -p ${NODE_NAME}/identity"
-printf "identity create ${NODE_NAME} --concurrency 32"
-printf "identity authorize ${NODE_NAME} '${AUTH_TOKEN}'"
-printf "mv ~/.local/share/storj/identity/${NODE_NAME}/* ${NODE_NAME}/identity"
-printf "rsync -avz ${NODE_NAME}/identity/ my-target"
+echo "Using node name: ${NODE_NAME}"
+echo "Create & authorize the identity file with the following commands, then move it to ${IDENTITY_DIR}"
+echo "This might take a while ... Run it on a powerful machine!\n"
+echo "mkdir -p ${NODE_NAME}/identity"
+echo "identity create ${NODE_NAME} --concurrency 32"
+echo "identity authorize ${NODE_NAME} '${AUTH_TOKEN}'"
+echo "mv ~/.local/share/storj/identity/${NODE_NAME}/* ${NODE_NAME}/identity"
+echo "rsync -avz ${NODE_NAME}/identity/ my-target"
 
 STORAGE="$(df -h ${DATA_ROOT} | awk 'NR==2 {print $4}')B"
 
@@ -57,17 +57,17 @@ DATA_ROOT=${DATA_ROOT}
 STORJ_SECRETS=${STORJ_SECRETS}
 EOF
 
-printf "\nPreparation of the node is complete. Execute the one-time setup by running:"
+printf "\nPreparation of the node is complete. Execute the one-time setup by running:\n"
 CMD_SETUP="sudo docker run --rm -e SETUP="true" \
     --user $(id -u):$(id -g) \
     --mount type=bind,source="${DATA_ROOT}/identity",destination=/app/identity \
     --mount type=bind,source="${DATA_ROOT}/config",destination=/app/config \
     --name storagenode storjlabs/storagenode:latest"
-printf ${CMD_SETUP}
+echo ${CMD_SETUP}
 
-printf "\nLaunch it by running:"
+printf "\nLaunch it by running:\n"
 CMD_LAUNCH="sudo docker compose -f insecure.docker-compose.yml --env-file ${DATA_ROOT}/.env up -d"
-printf ${CMD_LAUNCH}
+echo ${CMD_LAUNCH}
 
 INSTRUCTIONS_FILE=${DATA_ROOT}/instructions.sh
 cat <<EOF > ${INSTRUCTIONS_FILE}
